---
  # DEVICE ID
  DEVICE_ID: "DEVICE01"

  # Plant Port names
  PLANT_PORT_1: "Plant Port 1"
  PLANT_PORT_2: "Plant Port 2"

  # Pump port rasberry pin
  PUMP_PIN_1: 18    # BOARD = 12 | BCM = 18
  PUMP_PIN_2: 23    # BOARD = 16 | BCM = 23

  # The unique hostname that IoT; generated for this device.
  HOST_NAME: ""

  # Downloaded from IOT console
  ROOT_CA: "../credentials/AmazonRootCA1.pem"
  PRIVATE_KEY: "../credentials/private.pem.key"
  CERT_FILE: "../credentials/certificate.pem.crt"
  PORT: 8883

  MQTT_CLIENT: "plantPiClient"

  # AWS credentials
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""

  # Topics
  WATER_PLANT_TOPIC: "/sws/{deviceid}/{type}/waterplant"
  CREATE_SCHEDULE_TOPIC: "/sws/{deviceid}/{type}/createschedule"
  MOISTURE_STATS_TOPIC: "/sws/{deviceid}/{type}/moisturestats"

  REQUEST: "request"
  RESPONSE: "response"
