---
  # DEVICE ID
  DEVICE_ID: "DEVICE01"

  # The unique hostname that IoT; generated for this device.
  HOST_NAME: "a2r9hrtpe5nxqx-ats.iot.us-west-2.amazonaws.com"

  # Downloaded from IOT console
  ROOT_CA: "../credentials/AmazonRootCA1.pem"
  PRIVATE_KEY: "../credentials/private.pem.key"
  CERT_FILE: "../credentials/certificate.pem.crt"
  PORT: 8883

  MQTT_CLIENT: "plantPiClient"

  # Topics
  WATER_PLANT_TOPIC: "/sws/{deviceid}/{type}/waterplant"
  CREATE_SCHEDULE_TOPIC: "/sws/{deviceid}/{type}/createschedule"
  MOISTURE_STATS_TOPIC: "/sws/{deviceid}/{type}/moisturestats"

  REQUEST: "request"
  RESPONSE: "response"
